import { Sequelize } from "sequelize-typescript";
import {
  User,
  Action,
  Analysis,
  AnalysisArchive,
  AnalysisComment,
  Assessment,
  Dataset,
  DatasetAsset,
  Domain,
  Model,
  ModelParameter,
  Operation,
  Organization,
  Project,
  ProjectTag,
  Resource,
  Role,
  RolePermission,
  Upload,
  UserAOI,
  UserModel,
  UserModelClass,
  UserModelDataset,
  UserModelDatasetAnnotation,
  UserModelParameter,
  UserOrganization,
  UserProject,
  VulnerabilityType,
  Workspace,
  WorkspaceAssessment,
  WorkspaceModel,
  WorkspaceVulnerabilityType,
  LayerDetails,
  IndicesAppSentinelFormulas
} from "../portal-models"; // Import all your models here

const portalModels = [
  User,
  Action,
  Analysis,
  AnalysisArchive,
  AnalysisComment,
  Assessment,
  Dataset,
  DatasetAsset,
  Domain,
  Model,
  ModelParameter,
  Operation,
  Organization,
  Project,
  ProjectTag,
  Resource,
  Role,
  RolePermission,
  Upload,
  UserAOI,
  UserModel,
  UserModelClass,
  UserModelDataset,
  UserModelDatasetAnnotation,
  UserModelParameter,
  UserOrganization,
  UserProject,
  VulnerabilityType,
  Workspace,
  WorkspaceAssessment,
  WorkspaceModel,
  WorkspaceVulnerabilityType,
  LayerDetails,
  IndicesAppSentinelFormulas
];


export const portalSequelize = new Sequelize({
  database: process.env.PORTAL_DB_NAME || "portal",
  username: process.env.PORTAL_DB_USER || "user",
  password: process.env.PORTAL_DB_PASSWORD || "password",
  host: process.env.PORTAL_DB_HOST || "portal-db",
  port: Number(process.env.PORTAL_DB_PORT) || 5432,
  dialect: "postgres",
  models: portalModels,
});
